{% set version = '0.0.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-allelicseries
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/AllelicSeries_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/AllelicSeries/AllelicSeries_{{ version }}.tar.gz
  sha256: ff0a07553d400d1560576bf41ae98f8270c4831c84f2e36e6cf4d863f0b409f2

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/r.dll'        # [win]
    - '*/Rlapack.dll'  # [win]
    - '*/Rblas.dll'    # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
    - r-base
    - r-rnomni
    - r-rcpp
    - r-rcpparmadillo
    - r-skat
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rnomni
    - r-rcpp
    - r-rcpparmadillo
    - r-skat

test:
  commands:
    - $R -e "library('AllelicSeries')"           # [not win]
    - "\"%R%\" -e \"library('AllelicSeries')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=AllelicSeries
  license: BSD-3-Clause
  summary: 'Implementation of gene-level rare variant association tests targeting allelic series:
    genes where increasingly deleterious mutations have increasingly large phenotypic
    effects. The COding-variant Allelic Series Test (COAST) operates on the benign missense
    variants (BMVs), deleterious missense variants (DMVs), and protein truncating variants
    (PTVs) within a gene. COAST uses a set of adjustable weights that tailor the test
    towards rejecting the null hypothesis for genes where the average magnitude of effect
    increases monotonically from BMVs to DMVs to PTVs. See McCaw ZR, Somineni H, Bereket
    M, Klein C, Karaletsos T, Casale FP, Koller D, Soare TW. (2022) "An allelic series
    rare variant association test for candidate gene discovery" <doi:10.1101/2022.12.23.521658>.'
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
